defaultPortal: demo
portals:
  - name: demo
    portalId: 44945496
    env: prod
    authType: personalaccesskey
    auth:
      tokenInfo:
        accessToken: >-
          CM_a1JfRMRIRAA0AQAAA4C0DQAJYAgEAAMgY2KC3FSD4qI0eKO7pDDIUAFA7KISWVVwqJxMwJ5rUJPaNrh06OAAABEEAAAB4AAAAAAAAAAAAgAAAAAAABAAAwAcAjvAxPGAQBgBEAGBA_BgGABAgAwAAAAAAPAIDQhSkOsMBOBj1Fgd5H77T7Gn6nA4er0oDbmExUgBaAA
        expiresAt: '2024-01-16T15:47:54.344Z'
    personalAccessKey: >-
      CiQ0MGVlMzc3OS1kNTk3LTRkMmYtYmQ4ZS1mNjQyYjdkZjA2NmQQ2KC3FRj4qI0eKhkABeaRgrXRssh8xASUVBXFw2ajPcCajyZASgNuYTE
    sandboxAccountType: null
    parentAccountId: null
